services:
  - type: web
    name: loan-predictor-backend
    env: python
    buildCommand: pip install -r loan-predictor/backend/requirements.txt
    startCommand: gunicorn --chdir loan-predictor/backend --bind 0.0.0.0:$PORT app:app