services:
  - type: web
    name: loan-predictor-backend
    env: python
    buildCommand: cd loan-predictor/backend && pip install -r requirements.txt
    startCommand: cd loan-predictor/backend && gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.15